### ISSUE TITLE
Does this package work anymore?

### ISSUE THREAD

**Issue by rschwiebert** [adeel/google-scholar-scraper#2]
Cutting and pasting the README examples, I get zip. I notice, for example, the google link is still http.  Are the fixes easy or has google since drifted so that this is hard to fix?

**Comment by adeel** [comment]
Google Scholar doesn't have an official API, so I suppose this was bound to break at some point.  Does [scholar.py](https://github.com/ckreibich/scholar.py) do what you want?

**Comment by rschwiebert** [comment]
Doesn't quite work well enough to be useful for me, but thanks for the pointer anyway. Thanks for your help!
