### ISSUE TITLE
string out of index 

### ISSUE THREAD

**Issue by Akyuu1997** [adeel/google-scholar-scraper#3]
when put into one string, it will remind me that IndexError, such as this
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-7-8283dc99c838> in <module>
----> 1 gsscraper.get_result(query)

c:\users\dell\appdata\local\programs\python\python36\lib\site-packages\gsscraper.py in get_result(query)
     66
     67 def get_result(query):
---> 68   rs = get_results(query, 1)
     69   if rs:
     70     return rs[0]

c:\users\dell\appdata\local\programs\python\python36\lib\site-packages\gsscraper.py in get_results(query, count)
     63   html = _do_gscholar_request(GSCHOLAR_QUERY_PATH, gid, {"q": query}).text
     64   brs = _extract_bibtex_results(html, count, gid)
---> 65   return _parse_bibtex("\n".join(brs))
     66
     67 def get_result(query):

c:\users\dell\appdata\local\programs\python\python36\lib\site-packages\gsscraper.py in _parse_bibtex(bib)
     57
     58 def _parse_bibtex(bib):
---> 59   return bibtexparser.loads(bib).entries
     60
     61 def get_results(query, count):

c:\users\dell\appdata\local\programs\python\python36\lib\site-packages\bibtexparser\__init__.py in loads(bibtex_str, parser)
     46     if parser is None:
     47         parser = bparser.BibTexParser()
---> 48     return parser.parse(bibtex_str)
     49
     50

c:\users\dell\appdata\local\programs\python\python36\lib\site-packages\bibtexparser\bparser.py in parse(self, bibtex_str, partial)
    151         :rtype: BibDatabase
    152         """
--> 153         bibtex_file_obj = self._bibtex_file_obj(bibtex_str)
    154         try:
    155             self._expr.parseFile(bibtex_file_obj)

c:\users\dell\appdata\local\programs\python\python36\lib\site-packages\bibtexparser\bparser.py in _bibtex_file_obj(self, bibtex_str)
    223         if isinstance(bibtex_str, ustr):
    224             byte = ustr(byte, self.encoding, 'ignore')
--> 225             if bibtex_str[0] == byte:
    226                 bibtex_str = bibtex_str[1:]
    227         else:

IndexError: string index out of range

**Comment by shgo** [comment]
Having the same issue here.

**Comment by adeel** [comment]
Sorry, not sure this works anymore.  I would try [ckreibich/scholar.py](https://github.com/ckreibich/scholar.py).
